image: microsoft/dotnet:latest

stages:
    - build
    - test

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build NewAPIAutomated.sln"

test:
    stage: test
    script: 
        - "dotnet test UserStories.AcceptanceTests"
